### ISSUE TITLE
Inconsistent resize on Sketch 45.1

### ISSUE THREAD

**Issue by vic-georgiev** [kenmoore/sketch-relabel-button#32]
When I try to resize a small button group with longer text, the background sometimes ends short from the text — it doesn't honor the original padding of the group. This happens with the sample document provided. This same behavior doesn't occur if I do resize a symbol instead of a group.

![screen shot 1](https://user-images.githubusercontent.com/8484061/28079008-a56ccd24-661b-11e7-892b-7502e4443035.png)

Please please please fix this, as your plugin is my best new button plugin!!!

**Comment by kenmoore** [comment]
I just confirmed the plugin works fine in Sketch 44 and is broken in 45.  I've contacted the folks at Bohemian Coding to have them investigate. It's super frustrating the amount of time I have to spend fixing my plugin due to their API changes.  Will provide updates as I have them.

**Comment by vic-georgiev** [comment]
Thank you 👍

**Comment by bomberstudios** [comment]
Here's a PR that should fix this issue.

**Comment by kenmoore** [comment]
Awesome, thanks a bunch Ale!

**Comment by tbnv** [comment]
This behavior is still present. It's impossible to predict if the button background will have the proper width. Though, it looks like the problem doesn't occur with symbols but only with groups.

**Comment by kenmoore** [comment]
@tbnv I'm not seeing the issue in Sketch 53.2. A group will resize properly (though the selection bounding box may be the wrong size -- a new artifact which I haven't been able to fix). If you're seeing differently can you provide the exact steps to reproduce the issue, and the exact version of Sketch you're using? Thanks

**Comment by tbnv** [comment]
@kenmoore Oh my... I didn't realize that I didn't have the latest version of your plugin on this Mac (the other one was ok). Sorry about that!

FYI, it was not about the group size artifact, but really the background that wasn't resized properly. See here: https://shrrr.it/Screen-Recording-2019-03-15-17-22-47-XXUNwkYbSZ.gif
